name: Release
on:
  push:
    branches: [ master, 3.x, 2.x, 1.x ]

jobs:
  release:
    name: Node.js
    uses: node-modules/github-actions/.github/workflows/node-release.yml@master
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
    with:
      checkTest: false
      install: 'npm install --no-package-lock --no-fund'
